export const emails = [
  {
    id: "1",
    read: false,
    starred: true,
    from: "GitHub",
    fromEmail: "noreply@github.com",
    subject: "Your daily GitHub digest",
    preview: "You have 3 new notifications from your repositories...",
    time: "10:42 AM",
    workspace: "Work",
    hasAttachment: false,
  },
  {
    id: "2",
    read: true,
    starred: false,
    from: "Notion Team",
    fromEmail: "team@notion.so",
    subject: "What's new in Notion this month",
    preview:
      "Check out the latest features we've added to make your workflow even smoother...",
    time: "Yesterday",
    workspace: "Newsletters",
    hasAttachment: true,
  },
  {
    id: "3",
    read: false,
    starred: false,
    from: "Vercel",
    fromEmail: "notifications@vercel.com",
    subject: "Your project has been deployed",
    preview: "Your recent deployment to production completed successfully...",
    time: "Yesterday",
    workspace: "Work",
    hasAttachment: false,
  },
  {
    id: "4",
    read: true,
    starred: true,
    from: "Sarah Johnson",
    fromEmail: "sarah.j@example.com",
    subject: "Weekend plans",
    preview: "Hey! I was thinking we could meet up on Saturday for coffee...",
    time: "Jul 12",
    workspace: "Personal",
    hasAttachment: false,
  },
  {
    id: "5",
    read: true,
    starred: false,
    from: "Netflix",
    fromEmail: "info@netflix.com",
    subject: "New shows added to your list",
    preview: "We've added new shows that match your interests...",
    time: "Jul 11",
    workspace: "Newsletters",
    hasAttachment: false,
  },
  {
    id: "6",
    read: true,
    starred: false,
    from: "Bank of America",
    fromEmail: "customerservice@bofa.com",
    subject: "Your monthly statement is ready",
    preview: "Your statement for the period ending July 10 is now available...",
    time: "Jul 10",
    workspace: "Personal",
    hasAttachment: true,
  },
  {
    id: "7",
    read: true,
    starred: false,
    from: "LinkedIn",
    fromEmail: "notifications@linkedin.com",
    subject: "5 new connections for you",
    preview: "Expand your network with these connection suggestions...",
    time: "Jul 9",
    workspace: "Newsletters",
    hasAttachment: false,
  },
  {
    id: "8",
    read: true,
    starred: false,
    from: "Alex from Product Hunt",
    fromEmail: "alex@producthunt.com",
    subject: "Products you might be interested in",
    preview: "Here are some new products that match your interests...",
    time: "Jul 8",
    workspace: "Newsletters",
    hasAttachment: false,
  },
  {
    id: "9",
    read: true,
    starred: false,
    from: "Dropbox",
    fromEmail: "no-reply@dropbox.com",
    subject: "Someone shared a folder with you",
    preview: "Jane Doe has shared a folder called 'Project Assets' with you...",
    time: "Jul 7",
    workspace: "Work",
    hasAttachment: true,
  },
  {
    id: "10",
    read: true,
    starred: false,
    from: "Twitter",
    fromEmail: "info@twitter.com",
    subject: "Your weekly Twitter digest",
    preview: "See what's happening with the accounts you follow...",
    time: "Jul 6",
    workspace: "Newsletters",
    hasAttachment: false,
  },
  {
    id: "11",
    read: true,
    starred: false,
    from: "Google",
    fromEmail: "no-reply@google.com",
    subject: "Your Google Drive is ready",
    preview: "Your Google Drive is ready for use...",
    time: "Jul 5",
    workspace: "Work",
    hasAttachment: true,
  },
  {
    id: "12",
    read: true,
    starred: false,
    from: "Apple",
    fromEmail: "no-reply@apple.com",
    subject: "Your Apple ID is ready",
    preview: "Your Apple ID is ready for use...",
    time: "Jul 4",
    workspace: "Personal",
    hasAttachment: false,
  },
  {
    id: "13",
    read: true,
    starred: false,
    from: "Amazon",
    fromEmail: "no-reply@amazon.com",
    subject: "Your Amazon order is ready",
    preview: "Your order has been shipped and is on its way...",
    time: "Jul 3",
    workspace: "Work",
    hasAttachment: true,
  },
  {
    id: "14",
    read: true,
    starred: false,
    from: "Microsoft",
    fromEmail: "no-reply@microsoft.com",
    subject: "Your Microsoft account is ready",
    preview: "Your Microsoft account is ready for use...",
    time: "Jul 2",
    workspace: "Personal",
    hasAttachment: false,
  },
  {
    id: "15",
    read: true,
    starred: false,
    from: "Dropbox",
    fromEmail: "no-reply@dropbox.com",
    subject: "Someone shared a folder with you",
    preview: "Jane Doe has shared a folder called 'Project Assets' with you...",
    time: "Jul 1",
    workspace: "Work",
    hasAttachment: true,
  },
  {
    id: "16",
    read: true,
    starred: false,
    from: "Twitter",
    fromEmail: "info@twitter.com",
    subject: "Your weekly Twitter digest",
    preview: "See what's happening with the accounts you follow...",
    time: "Jul 6",
    workspace: "Newsletters",
    hasAttachment: false,
  },
  {
    id: "17",
    read: true,
    starred: false,
    from: "Google",
    fromEmail: "no-reply@google.com",
    subject: "Your Google Drive is ready",
    preview: "Your Google Drive is ready for use...",
    time: "Jul 5",
    workspace: "Work",
    hasAttachment: true,
  },
];
